### ISSUE TITLE
Agregar un ejemplo de la imagen resultante

### ISSUE THREAD

**Issue by Gyga8K** [ljesparis/glsb#1]
Seria bueno que agregues un ejemplo de la imagen resultante, para que los usuarios sepamos cual es el resultado de utilizar la herramienta sin tener que descargarla y compilarla.

**Comment by ljesparis** [comment]
@Gyga8K si, pero ... igual tendrían que descargar la herramienta para ver el mensaje oculto. No hay mucha diferencia entre la imagen con el mensaje y la imagen sin el mensaje.
